apiVersion: networking.istio.io/v1beta1
kind: DestinationRule
metadata:
  name: helloworld-cb
  namespace: sample
spec:
  host: helloworld
  trafficPolicy:
    outlierDetection:
      consecutive5xxErrors: 3
      interval: 10s
      baseEjectionTime: 30s
      maxEjectionPercent: 50
