apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: helloworld-retry
  namespace: sample
spec:
  hosts:
  - helloworld
  http:
  - route:
    - destination:
        host: helloworld
    retries:
      attempts: 3
      perTryTimeout: 2s
      retryOn: 5xx,reset,connect-failure
